spring:
  datasource:
    url: jdbc:mysql://localhost:3306/albergodb?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
